export const GET_HOME_SHOWS_LOADING = 'GET_HOME_SHOWS_LOADING';
export const GET_HOME_SHOWS_LOADED = 'GET_HOME_SHOWS_LOADED';
export const GET_HOME_SHOWS_FAIL = 'GET_HOME_SHOWS_FAIL';


export const GET_MOVIE_SHOWS_LOADING = 'GET_MOVIE_SHOWS_LOADING';
export const GET_MOVIE_SHOWS_LOADED = 'GET_MOVIE_SHOWS_LOADED';
export const GET_MOVIE_SHOWS_FAIL = 'GET_MOVIE_SHOWS_FAIL';


export const GET_SERIES_SHOWS_LOADING = 'GET_SERIES_SHOWS_LOADING';
export const GET_SERIES_SHOWS_LOADED = 'GET_SERIES_SHOWS_LOADED';
export const GET_SERIES_SHOWS_FAIL = 'GET_SERIES_SHOWS_FAIL';


export const GET_MOVIE_DETTAIL_LOADING = 'GET_MOVIE_DETTAIL_LOADING';
export const GET_MOVIE_DETTAIL_LOADED = 'GET_MOVIE_DETTAIL_LOADED';
export const GET_MOVIE_DETTAIL_FAIL = 'GET_MOVIE_DETTAIL_FAIL';


export const GET_SERIES_DETTAIL_LOADING = 'GET_SERIES_DETTAIL_LOADING';
export const GET_SERIES_DETTAIL_LOADED = 'GET_SERIES_DETTAIL_LOADED';
export const GET_SERIES_DETTAIL_FAIL = 'GET_SERIES_DETTAIL_FAIL';

export const SEARCH_LOADING = 'SEARCH_LOADING';
export const SEARCH_LOADED = 'SEARCH_LOADED';
export const SEARCH_FAIL = 'SEARCH_FAIL';