export const GET_HOME_SHOWS_LOADING = 'GET_HOME_SHOWS_LOADING';
export const GET_HOME_SHOWS_LOADED = 'GET_HOME_SHOWS_LOADED';
export const GET_HOME_SHOWS_FAIL = 'GET_HOME_SHOWS_FAIL';

export const GET_MOVIE_SHOWS_LOADING = 'GET_MOVIE_SHOWS_LOADING';
export const GET_MOVIE_SHOWS_LOADED = 'GET_MOVIE_SHOWS_LOADED';
export const GET_MOVIE_SHOWS_FAIL = 'GET_MOVIE_SHOWS_FAIL';

export const GET_SERIES_SHOWS_LOADING = 'GET_SERIES_SHOWS_LOADING';
export const GET_SERIES_SHOWS_LOADED = 'GET_SERIES_SHOWS_LOADED';
export const GET_SERIES_SHOWS_FAIL = 'GET_SERIES_SHOWS_FAIL';

export const GET_MOVIE_DETTAIL_LOADING = 'GET_MOVIE_DETTAIL_LOADING';
export const GET_MOVIE_DETTAIL_LOADED = 'GET_MOVIE_DETTAIL_LOADED';
export const GET_MOVIE_DETTAIL_FAIL = 'GET_MOVIE_DETTAIL_FAIL';
export const ADD_OR_DELETE_MOVIE_LIST = 'ADD_OR_DELETE_MOVIE_LIST';
export const ADD_OR_DELETE_MOVIE_LIST_ERROR = 'ADD_OR_DELETE_MOVIE_LIST_ERROR'

export const GET_SERIES_DETTAIL_LOADING = 'GET_SERIES_DETTAIL_LOADING';
export const GET_SERIES_DETTAIL_LOADED = 'GET_SERIES_DETTAIL_LOADED';
export const GET_SERIES_DETTAIL_FAIL = 'GET_SERIES_DETTAIL_FAIL';
export const ADD_OR_DELETE_SERIES_LIST = 'ADD_OR_DELETE_SERIES_LIST';
export const ADD_OR_DELETE_SERIES_LIST_ERROR = 'ADD_OR_DELETE_SERIES_LIST_ERROR'

export const SEARCH_LOADING = 'SEARCH_LOADING';
export const SEARCH_LOADED = 'SEARCH_LOADED';
export const SEARCH_FAIL = 'SEARCH_FAIL';

export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const USER_FAIL = 'USER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';